### ISSUE TITLE
[Bug]: hybrid videos don't support video files

### ISSUE THREAD

**Issue by iamsuper123** [deforum-art/sd-forge-deforum#11]
### What happened and why was it ungood?

when I use controlnet and insert a video file path to the box that clearly says "insert video/image path" it says that videos are not supported. only "jpg, bmp, png,"ect formats are supported. I know this isn't controlnet's problem because the errors in the terminal are all caused by deforum python scripts.
can someone help me with this? is there an alternative way to generate hybrid videos using controlnet with forge or another optimized version of stable diffusion?

**Comment by rewbs** [comment]
This is resolved. Videos are working correctly.
