### ISSUE TITLE
What are the folder / filename formats for this extension?

### ISSUE THREAD

**Issue by MrMxyzptlk** [deforum-art/sd-forge-deforum#14]
### What happened and why was it ungood?

I can't figure out how to format the 'batchname' so that the completed videos are in the naming format of folder"Deforum"/"Date" and the filename would be the same as all other txt2img / img2img files. I.E.
a Filename of 0003 - 1302452.mp4 under the folder ...Deforum/02-23-2024

...Deforum/02-23-2024/0003 - 1302452.mp4 would be the path.

Is this possible? 

I've tried using the SD-WEBUI-Forge naming formats to no avail.

**Comment by rewbs** [comment]
Hi, this isn't exactly what you're asking for, but it might be close enough. I've just pushed an update that allows you to specify `{date}` in the batch name, and it will be substituted as expected.

The batch name is used as the sub-folder that will include all the output (images, videos, text metadata, srt etc...). That folder is placed within the img2img output folder that you have configured in Forge. The video filename is always the "timestring" (which is a date-time string), plus some suffix if it has had post-processing (upscaling and/or interpolation).

So the full path to the video is `<img2img_path>/<batch_name>/<timestring>[_suffix].mp4`, where `<batch_name>` can now include the date.

Aside from the newly added `{date}`, the list of values you can substitute into your batch name is basically all the values in your settings.txt file (so `{seed}`, `{w}`, `{h}`, `{prompts}` etc...). Note that is different from the string substitutions that are available in other a1111/forge settings paths outside of Deforum that are documented on https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Custom-Images-Filename-Name-and-Subdirectory  .

Is this good enough for your use case?

**Comment by MrMxyzptlk** [comment]
Yes this great; however when I changed the batchname to {date}, it creates a folder named "date", rather than 2024-09-04?

Also as a side question, how do I prevent it from creating a preview video everytime?

Thank you.

**Comment by rewbs** [comment]
> Yes this great; however when I changed the batchname to {date}, it creates a folder named "date", rather than 2024-09-04?

That suggests you're not on the latest version of the extension. Can you update and try again?

> Also as a side question, how do I prevent it from creating a preview video everytime?

In the Forge settings, go to the Deforum section and you will see an option there to configure whether you want preview videos.

**Comment by MrMxyzptlk** [comment]
Great! OK, the preview option is now disabled, and date is working; thank you!
The only 'gotcha', is there a way for you to change or option for date to work like the rest of sd-webui-forge?

For instance txt2img creates folders in the format: 2024-04-10 and Deforum creates them in this format: 20240410.
The former is easier on the eyes ; )

Another example is AnimateDiff create a folder called "AnimateDiff" and then a folder inside of that call "2024-04-10" with a the file inside of the date folder.

Thank you.

**Comment by Vendaciousness** [comment]
I like it the way it is.

**Comment by MrMxyzptlk** [comment]
Ok...

**Comment by Vendaciousness** [comment]
If you still have unanswered questions, or would like to discuss Deforum with other users, they have a really great Discord server filled with resources here: [https://discord.gg/deforum](https://discord.gg/deforum)
