### ISSUE TITLE
[Bug]: No Deforum tab if you install from URL

### ISSUE THREAD

**Issue by robertJene** [deforum-art/sd-forge-deforum#15]
### What happened and why was it ungood?

there is no Deforum tab at all in Forge

**Comment by rewbs** [comment]
Hi! That suggests that the extension is not correctly installed. Please:
- Ensure you have followed the installation instructions from the README as best as you can.
- Check your extension directory to ensure it contains a subdirectory with the contents of this repository.
- Confirm there are no other deforum extensions in the extensions directory.
- Check the Forge log for errors on startup.

Thanks!

**Comment by rewbs** [comment]
Closing as this is most likely a usage issue. Feel free to reopen or open another bug if you discover otherwise.

**Comment by robertJene** [comment]
OK Got the tab to install by following the instructions on the Deforum for Forge page.

Now Deforum says this on the run tab:
**ControlNet not found. Please install it :)**

But Forge has Control Net built-in

*edit
I was expecting Deforum for Forge to be able to install from the "Install from URL" option in Forge
