### ISSUE TITLE
[Bug]: can't use video input with

### ISSUE THREAD

**Issue by squarevale** [deforum-art/sd-forge-deforum#7]
### What happened and why was it ungood?

seems to be a bug when using a video input in a controlnet unit

`<video_path> has format 'mp4', which is not supported. Supported formats are: ['png', 'jpg', 'jpeg', 'bmp']'.`

**Comment by rewbs** [comment]
Thanks! Fixed via: https://github.com/deforum-art/sd-forge-deforum/pull/9
